/*
 * Real poster + localized kind chips for Solution template cards.
 * Posters are mirrored from the Open Design project's manifest poster /
 * baked previews CDN into public/previews/plugins/<manifest-id>.* (the
 * same resolution chain template-card.astro uses). Kind labels are the
 * zh-CN taxonomy chips rendered by the live site (原型 / 演示文稿 / 视频 / 图像).
 */

export type SolutionCardMedia = { poster: string; kind: string };

// Keyed by the same /plugins/<slug>/ hrefs as SOLUTION_PLUGIN_CARDS.
export const SOLUTION_CARD_MEDIA: Record<string, SolutionCardMedia> = {
  '/plugins/example-blog-post/': { poster: '/previews/plugins/example-blog-post.jpg', kind: '原型' },
  '/plugins/example-dashboard/': { poster: '/previews/plugins/example-dashboard.jpg', kind: '原型' },
  '/plugins/example-data-report/': { poster: '/previews/plugins/example-data-report.jpg', kind: '原型' },
  '/plugins/example-deck-guizang-editorial/': { poster: '/previews/plugins/example-deck-guizang-editorial.jpg', kind: '演示文稿' },
  '/plugins/example-deck-open-slide-canvas/': { poster: '/previews/plugins/example-deck-open-slide-canvas.jpg', kind: '演示文稿' },
  '/plugins/example-deck-swiss-international/': { poster: '/previews/plugins/example-deck-swiss-international.jpg', kind: '演示文稿' },
  '/plugins/example-digital-eguide/': { poster: '/previews/plugins/example-digital-eguide.jpg', kind: '原型' },
  '/plugins/example-docs-page/': { poster: '/previews/plugins/example-docs-page.jpg', kind: '原型' },
  '/plugins/example-email-marketing/': { poster: '/previews/plugins/example-email-marketing.jpg', kind: '原型' },
  '/plugins/example-eng-runbook/': { poster: '/previews/plugins/example-eng-runbook.jpg', kind: '原型' },
  '/plugins/example-finance-report/': { poster: '/previews/plugins/example-finance-report.jpg', kind: '原型' },
  '/plugins/example-flowai-live-dashboard-template/': { poster: '/previews/plugins/example-flowai-live-dashboard-template.jpg', kind: '原型' },
  '/plugins/example-gamified-app/': { poster: '/previews/plugins/example-gamified-app.jpg', kind: '原型' },
  '/plugins/example-github-dashboard/': { poster: '/previews/plugins/example-github-dashboard.jpg', kind: '原型' },
  '/plugins/example-hr-onboarding/': { poster: '/previews/plugins/example-hr-onboarding.jpg', kind: '原型' },
  '/plugins/example-html-ppt-graphify-dark-graph/': { poster: '/previews/plugins/example-html-ppt-graphify-dark-graph.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-knowledge-arch-blueprint/': { poster: '/previews/plugins/example-html-ppt-knowledge-arch-blueprint.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-obsidian-claude-gradient/': { poster: '/previews/plugins/example-html-ppt-obsidian-claude-gradient.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-pitch-deck/': { poster: '/previews/plugins/example-html-ppt-pitch-deck.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-product-launch/': { poster: '/previews/plugins/example-html-ppt-product-launch.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-tech-sharing/': { poster: '/previews/plugins/example-html-ppt-tech-sharing.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-xhs-white-editorial/': { poster: '/previews/plugins/example-html-ppt-xhs-white-editorial.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-zhangzara-biennale-yellow/': { poster: '/previews/plugins/example-html-ppt-zhangzara-biennale-yellow.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-zhangzara-bold-poster/': { poster: '/previews/plugins/example-html-ppt-zhangzara-bold-poster.jpg', kind: '演示文稿' },
  '/plugins/example-html-ppt-zhangzara-editorial-tri-tone/': { poster: '/previews/plugins/example-html-ppt-zhangzara-editorial-tri-tone.jpg', kind: '演示文稿' },
  '/plugins/example-ib-pitch-book/': { poster: '/previews/plugins/example-ib-pitch-book.jpg', kind: '演示文稿' },
  '/plugins/example-image-poster/': { poster: '/previews/plugins/example-image-poster.jpg', kind: '图像' },
  '/plugins/example-kami-landing/': { poster: '/previews/plugins/example-kami-landing.jpg', kind: '原型' },
  '/plugins/example-kanban-board/': { poster: '/previews/plugins/example-kanban-board.jpg', kind: '原型' },
  '/plugins/example-last30days/': { poster: '/previews/plugins/example-last30days.png', kind: '原型' },
  '/plugins/example-meeting-notes/': { poster: '/previews/plugins/example-meeting-notes.jpg', kind: '原型' },
  '/plugins/example-mobile-app/': { poster: '/previews/plugins/example-mobile-app.jpg', kind: '原型' },
  '/plugins/example-mobile-onboarding/': { poster: '/previews/plugins/example-mobile-onboarding.jpg', kind: '原型' },
  '/plugins/example-mockup-device-3d/': { poster: '/previews/plugins/example-mockup-device-3d.jpg', kind: '原型' },
  '/plugins/example-pm-spec/': { poster: '/previews/plugins/example-pm-spec.jpg', kind: '原型' },
  '/plugins/example-saas-landing/': { poster: '/previews/plugins/example-saas-landing.jpg', kind: '原型' },
  '/plugins/example-simple-deck/': { poster: '/previews/plugins/example-simple-deck.jpg', kind: '演示文稿' },
  '/plugins/example-social-carousel/': { poster: '/previews/plugins/example-social-carousel.jpg', kind: '原型' },
  '/plugins/example-team-okrs/': { poster: '/previews/plugins/example-team-okrs.jpg', kind: '原型' },
  '/plugins/example-web-prototype-taste-brutalist/': { poster: '/previews/plugins/example-web-prototype-taste-brutalist.jpg', kind: '原型' },
  '/plugins/example-web-prototype-taste-editorial/': { poster: '/previews/plugins/example-web-prototype-taste-editorial.jpg', kind: '原型' },
  '/plugins/example-web-prototype-taste-soft/': { poster: '/previews/plugins/example-web-prototype-taste-soft.jpg', kind: '原型' },
  '/plugins/example-web-prototype/': { poster: '/previews/plugins/example-web-prototype.jpg', kind: '原型' },
  '/plugins/example-weekly-update/': { poster: '/previews/plugins/example-weekly-update.jpg', kind: '演示文稿' },
  '/plugins/example-wireframe-sketch/': { poster: '/previews/plugins/example-wireframe-sketch.jpg', kind: '原型' },
  '/plugins/image-template-3d-stone-staircase-evolution-infographic/': { poster: '/previews/plugins/image-template-3d-stone-staircase-evolution-infographic.jpg', kind: '图像' },
  '/plugins/image-template-anime-martial-arts-battle-illustration/': { poster: '/previews/plugins/image-template-anime-martial-arts-battle-illustration.jpg', kind: '图像' },
  '/plugins/image-template-e-commerce-live-stream-ui-mockup/': { poster: '/previews/plugins/image-template-e-commerce-live-stream-ui-mockup.jpg', kind: '图像' },
  '/plugins/image-template-game-screenshot-three-kingdoms-guanyu-slaying-yanliang/': { poster: '/previews/plugins/image-template-game-screenshot-three-kingdoms-guanyu-slaying-yanliang.jpg', kind: '图像' },
  '/plugins/image-template-illustrated-city-food-map/': { poster: '/previews/plugins/image-template-illustrated-city-food-map.jpg', kind: '图像' },
  '/plugins/image-template-momotaro-explainer-slide-in-hybrid-style/': { poster: '/previews/plugins/image-template-momotaro-explainer-slide-in-hybrid-style.jpg', kind: '图像' },
  '/plugins/image-template-profile-avatar-cinematic-south-asian-male-portrait-with-vultures/': { poster: '/previews/plugins/image-template-profile-avatar-cinematic-south-asian-male-portrait-with-vultures.jpg', kind: '图像' },
  '/plugins/image-template-social-media-post-showa-day-retro-culture-magazine-cover/': { poster: '/previews/plugins/image-template-social-media-post-showa-day-retro-culture-magazine-cover.jpg', kind: '图像' },
  '/plugins/image-template-vr-headset-exploded-view-poster/': { poster: '/previews/plugins/image-template-vr-headset-exploded-view-poster.jpg', kind: '图像' },
  '/plugins/video-template-3d-animated-boy-building-lego/': { poster: '/previews/plugins/video-template-3d-animated-boy-building-lego.jpg', kind: '视频' },
  '/plugins/video-template-ancient-indian-kingdom-fpv-video/': { poster: '/previews/plugins/video-template-ancient-indian-kingdom-fpv-video.jpg', kind: '视频' },
  '/plugins/video-template-cinematic-dragon-interaction-flight/': { poster: '/previews/plugins/video-template-cinematic-dragon-interaction-flight.jpg', kind: '视频' },
  '/plugins/video-template-cinematic-street-racing-sequence-for-seedance-2/': { poster: '/previews/plugins/video-template-cinematic-street-racing-sequence-for-seedance-2.jpg', kind: '视频' },
  '/plugins/video-template-cinematic-vampire-alley-fight-sequence/': { poster: '/previews/plugins/video-template-cinematic-vampire-alley-fight-sequence.jpg', kind: '视频' },
  '/plugins/video-template-crimson-horizon-sci-fi-cinematic-sequence/': { poster: '/previews/plugins/video-template-crimson-horizon-sci-fi-cinematic-sequence.jpg', kind: '视频' },
  '/plugins/video-template-cyberpunk-game-trailer-script/': { poster: '/previews/plugins/video-template-cyberpunk-game-trailer-script.jpg', kind: '视频' },
  '/plugins/video-template-live-action-anime-adaptation-water-vs-thunder-breathing-duel/': { poster: '/previews/plugins/video-template-live-action-anime-adaptation-water-vs-thunder-breathing-duel.jpg', kind: '视频' },
  '/plugins/video-template-luxury-supercar-cinematic-narrative/': { poster: '/previews/plugins/video-template-luxury-supercar-cinematic-narrative.jpg', kind: '视频' },
};
