/*
 * Featured plugin / design-system cards for Solution detail pages.
 * Extracted from the Open Design project (soia Website) —
 *   plugins/_official/<bucket>/<dir>/open-design.json
 *   data/plugin-previews/manifest.json + app/_lib/system-l10n.ts
 * Titles/descriptions are zh-CN i18n; `poster` is the locally mirrored
 * preview image under /previews/plugins/ (downloaded from the manifest
 * poster or the baked previews CDN); `kind` is the localized mode label.
 */

export type SolutionCard = { title: string; desc: string; href: string; poster?: string; kind?: string };

export const SOLUTION_PLUGIN_CARDS: Record<string, SolutionCard[]> = {
  'prototype': [
    {
      title: "网页原型",
      desc: "通用桌面网页原型。通过复制种子文件 `assets/template.html` 并粘贴 `references/layouts.md` 中的布局生成单个独立 HTML 文件。适用于落地页、营销页、文档或 SaaS 页面的默认选项。",
      href: '/plugins/example-web-prototype/',
      poster: "/previews/plugins/example-web-prototype.jpg",
      kind: "原型",
    },
    {
      title: "移动应用",
      desc: "在页面中渲染于像素级精确的 iPhone 15 Pro 框架内的移动应用屏幕。通过复制种子文件 assets/template.html 并粘贴 references/layouts.md 中的一个屏幕原型来构建。当需求提到《移动应用》、《iOS 应用》、《Android 应用》、《手机屏幕》或《应用 UI》时使用。",
      href: '/plugins/example-mobile-app/',
      poster: "/previews/plugins/example-mobile-app.jpg",
      kind: "原型",
    },
    {
      title: "SaaS 落地页",
      desc: "单页 SaaS 落地页，包含主视觉、功能特性、社会证明、价格方案和行动号召。遵循当前 DESIGN.md 的颜色/排版/布局规范。触发关键词：\"saas landing\"、\"marketing page\"、\"product landing\"。",
      href: '/plugins/example-saas-landing/',
      poster: "/previews/plugins/example-saas-landing.jpg",
      kind: "原型",
    },
    {
      title: "游戏化应用",
      desc: "三屏手机原型展示游戏化应用界面：封面海报、每日任务与经验值进度条、任务详情。适用于游戏化应用、习惯追踪、RPG 风格生活应用、升级系统、每日任务、XP/连击应用等需求。",
      href: '/plugins/example-gamified-app/',
      poster: "/previews/plugins/example-gamified-app.jpg",
      kind: "原型",
    },
    {
      title: "员工入职",
      desc: "单页新员工入职计划——第一周日程安排、伙伴+经理介绍、学习路径、设备清单以及'完成标志'目标。当需求提及'入职'、'新员工'、'第一周计划'或'onboarding'时使用。",
      href: '/plugins/example-hr-onboarding/',
      poster: "/previews/plugins/example-hr-onboarding.jpg",
      kind: "原型",
    },
    {
      title: "Kami Landing",
      desc: "生成印刷级单页纸质文档——温暖羊皮纸底色、墨蓝强调色、单一衬线字重，无斜体，无冷灰。输出呈现专业白皮书或工作室单页效果，而非应用 UI。原生多语言支持（EN · zh-CN · ja）。单个独立 HTML 文件，零依赖。",
      href: '/plugins/example-kami-landing/',
      poster: "/previews/plugins/example-kami-landing.jpg",
      kind: "原型",
    },
  ],
  'dashboard': [
    {
      title: "仪表盘",
      desc: "单文件 HTML 管理/分析仪表盘。固定左侧边栏，顶部用户/搜索栏，主区域显示 KPI 卡片网格和图表。适用于需要'仪表盘'、'管理后台'、'数据分析'或'控制面板'界面的场景。",
      href: '/plugins/example-dashboard/',
      poster: "/previews/plugins/example-dashboard.jpg",
      kind: "原型",
    },
    {
      title: "GitHub 仪表板",
      desc: "GitHub 仓库分析仪表板 — 星标、分支、贡献者、议题、拉取请求、近期活动和主要贡献者。适用于 GitHub 仓库仪表板、开源增长报告、仓库健康页面或 GitHub 分析视图。",
      href: '/plugins/example-github-dashboard/',
      poster: "/previews/plugins/example-github-dashboard.jpg",
      kind: "原型",
    },
    {
      title: "数据可视化报告",
      desc: "把 CSV/Excel/JSON 数据转成漂亮的可视化报告页",
      href: '/plugins/example-data-report/',
      poster: "/previews/plugins/example-data-report.jpg",
      kind: "原型",
    },
    {
      title: "财务报告",
      desc: "季度/月度财务报告——包含关键指标的报头、收入与消耗图表、损益汇总表、重点摘要和展望段落。当需求提到'财务报告'、'Q3报告'、'MRR审查'、'P&L'或'财报'时使用。",
      href: '/plugins/example-finance-report/',
      poster: "/previews/plugins/example-finance-report.jpg",
      kind: "原型",
    },
    {
      title: "最近30天",
      desc: "最近30天的社区和社交趋势研究。适用于了解当前舆论、近期情绪、社区反应、社交证明、发布反馈、趋势扫描或最近30天的背景信息。",
      href: '/plugins/example-last30days/',
      poster: "/previews/plugins/example-last30days.png",
      kind: "原型",
    },
    {
      title: "Flowai 实时仪表板模板",
      desc: "FlowAI 风格的团队管理仪表板，包含三个标签页（团队成员、团队详情、活动日志）、KPI 统计行、成员表格、角色分布条形图、在线状态和活动趋势图、顶级贡献者面板，支持亮暗主题切换、图表悬停提示、面板点击缩放和 CSV 导出功能。",
      href: '/plugins/example-flowai-live-dashboard-template/',
      poster: "/previews/plugins/example-flowai-live-dashboard-template.jpg",
      kind: "原型",
    },
  ],
  'slides': [
    {
      title: "像顶级加速器合伙人一样写 Demo Day 路演",
      desc: "像顶级加速器合伙人一样写 Demo Day 路演——一份可商业交付的融资路演 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-pitch-deck/',
      poster: "/previews/plugins/example-html-ppt-pitch-deck.jpg",
      kind: "演示文稿",
    },
    {
      title: "像战略客户 AE 一样推动团队落地",
      desc: "像战略客户 AE 一样推动团队落地——一份可商业交付的B2B 销售 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-product-launch/',
      poster: "/previews/plugins/example-html-ppt-product-launch.jpg",
      kind: "演示文稿",
    },
    {
      title: "像 Principal PM 一样写功能商业论证",
      desc: "像 Principal PM 一样写功能商业论证——一份可商业交付的产品管理 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-graphify-dark-graph/',
      poster: "/previews/plugins/example-html-ppt-graphify-dark-graph.jpg",
      kind: "演示文稿",
    },
    {
      title: "像平台 VP 一样把事故复盘写成学习稿",
      desc: "像平台 VP 一样把事故复盘写成学习稿——一份可商业交付的产品管理 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-knowledge-arch-blueprint/',
      poster: "/previews/plugins/example-html-ppt-knowledge-arch-blueprint.jpg",
      kind: "演示文稿",
    },
    {
      title: "像财富 500 强董事长一样写董事会预读",
      desc: "像财富 500 强董事长一样写董事会预读——一份可商业交付的企业战略 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-deck-swiss-international/',
      poster: "/previews/plugins/example-deck-swiss-international.jpg",
      kind: "演示文稿",
    },
    {
      title: "像企业 AI 转型负责人一样写落地简报",
      desc: "像企业 AI 转型负责人一样写落地简报——一份可商业交付的AI 素养 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-obsidian-claude-gradient/',
      poster: "/previews/plugins/example-html-ppt-obsidian-claude-gradient.jpg",
      kind: "演示文稿",
    },
    {
      title: "像一线 VC 合伙人一样写 A 轮增长叙事",
      desc: "像一线 VC 合伙人一样写 A 轮增长叙事——一份可商业交付的融资路演 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-zhangzara-bold-poster/',
      poster: "/previews/plugins/example-html-ppt-zhangzara-bold-poster.jpg",
      kind: "演示文稿",
    },
    {
      title: "像美术馆策展总监一样做双年展策展稿",
      desc: "像美术馆策展总监一样做双年展策展稿——一份可商业交付的设计打磨 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-zhangzara-biennale-yellow/',
      poster: "/previews/plugins/example-html-ppt-zhangzara-biennale-yellow.jpg",
      kind: "演示文稿",
    },
    {
      title: "像成长股权分析师一样写投资 Pitch Book",
      desc: "像成长股权分析师一样写投资 Pitch Book——一份可商业交付的融资路演 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-ib-pitch-book/',
      poster: "/previews/plugins/example-ib-pitch-book.jpg",
      kind: "演示文稿",
    },
  ],
  'image': [
    {
      title: "3D 石制楼梯进化信息图",
      desc: "将平面进化时间线转换为逼真的 3D 石制楼梯信息图，包含详细的生物渲染和结构化侧边面板。",
      href: '/plugins/image-template-3d-stone-staircase-evolution-infographic/',
      poster: "/previews/plugins/image-template-3d-stone-staircase-evolution-infographic.jpg",
      kind: "图像",
    },
    {
      title: "手绘美食地图插画",
      desc: "生成手绘水彩风格的旅游地图，展示带编号的当地特色美食、地标建筑和图例说明。",
      href: '/plugins/image-template-illustrated-city-food-map/',
      poster: "/previews/plugins/image-template-illustrated-city-food-map.jpg",
      kind: "图像",
    },
    {
      title: "电商直播界面模型",
      desc: "生成逼真的社交媒体直播界面，叠加在人像上，支持自定义聊天消息、礼物弹窗和商品购买卡片。",
      href: '/plugins/image-template-e-commerce-live-stream-ui-mockup/',
      poster: "/previews/plugins/image-template-e-commerce-live-stream-ui-mockup.jpg",
      kind: "图像",
    },
    {
      title: "游戏截图 - 三国ARPG：关羽斩颜良",
      desc: "《Black Myth: Wukong》风格的三国题材ARPG游戏截图，展现关羽骑赤兔马在暴雨战场冲向敌将颜良的经典场景，采用Unreal Engine 5渲染，第三人称视角，包含完整Boss战HUD界面。16:9比例，适配gpt-image-2。",
      href: '/plugins/image-template-game-screenshot-three-kingdoms-guanyu-slaying-yanliang/',
      poster: "/previews/plugins/image-template-game-screenshot-three-kingdoms-guanyu-slaying-yanliang.jpg",
      kind: "图像",
    },
    {
      title: "社交媒体帖子 - 昭和之日复古文化杂志封面",
      desc: "温馨编辑风格的日本节日特色页面，结合动漫角色艺术、怀旧的Showa时代街景图像和杂志风格的信息布局，适用于季节性文化推广。",
      href: '/plugins/image-template-social-media-post-showa-day-retro-culture-magazine-cover/',
      poster: "/previews/plugins/image-template-social-media-post-showa-day-retro-culture-magazine-cover.jpg",
      kind: "图像",
    },
    {
      title: "VR头显爆炸视图海报",
      desc: "生成高科技风格的VR头显爆炸视图，包含详细的组件标注和宣传文案。",
      href: '/plugins/image-template-vr-headset-exploded-view-poster/',
      poster: "/previews/plugins/image-template-vr-headset-exploded-view-poster.jpg",
      kind: "图像",
    },
    {
      title: "动漫武术对战插画",
      desc: "生成动态高冲击力的动漫插画，描绘两位女性角色在传统道场中使用元素能量特效进行战斗。",
      href: '/plugins/image-template-anime-martial-arts-battle-illustration/',
      poster: "/previews/plugins/image-template-anime-martial-arts-battle-illustration.jpg",
      kind: "图像",
    },
    {
      title: "个人资料 / 头像 - 电影感南亚男性肖像与秃鹫",
      desc: "一幅充满氛围感的南亚年轻男性肖像，置身于黑暗奇幻场景中，周围环绕着秃鹫和乌鸦。",
      href: '/plugins/image-template-profile-avatar-cinematic-south-asian-male-portrait-with-vultures/',
      poster: "/previews/plugins/image-template-profile-avatar-cinematic-south-asian-male-portrait-with-vultures.jpg",
      kind: "图像",
    },
    {
      title: "桃太郎解说幻灯片混合风格",
      desc: "结合 Irasutoya 插画简洁温暖的美学与日本政府幻灯片高信息密度特征的提示词。",
      href: '/plugins/image-template-momotaro-explainer-slide-in-hybrid-style/',
      poster: "/previews/plugins/image-template-momotaro-explainer-slide-in-hybrid-style.jpg",
      kind: "图像",
    },
  ],
  'video': [
    {
      title: "深红地平线科幻电影序列",
      desc: "科幻电影《深红地平线》的完整9镜头电影视频序列，涵盖从火箭发射到火星上诡异外星人遭遇的所有场景。",
      href: '/plugins/video-template-crimson-horizon-sci-fi-cinematic-sequence/',
      poster: "/previews/plugins/video-template-crimson-horizon-sci-fi-cinematic-sequence.jpg",
      kind: "视频",
    },
    {
      title: "3D动画男孩搭建Lego",
      desc: "3D动画风格的多镜头视频提示，描绘男孩在房间中仔细组装Lego积木，带有延时摄影效果。",
      href: '/plugins/video-template-3d-animated-boy-building-lego/',
      poster: "/previews/plugins/video-template-3d-animated-boy-building-lego.jpg",
      kind: "视频",
    },
    {
      title: "真人版动漫改编：水之呼吸与雷之呼吸对决",
      desc: "生成动漫风格真人对决场景的详细提示词，展现「水之呼吸」（蓝色水龙）与「雷之呼吸」（金色闪电）的 15 秒战斗画面。",
      href: '/plugins/video-template-live-action-anime-adaptation-water-vs-thunder-breathing-duel/',
      poster: "/previews/plugins/video-template-live-action-anime-adaptation-water-vs-thunder-breathing-duel.jpg",
      kind: "视频",
    },
    {
      title: "Seedance 2 电影级街头赛车序列",
      desc: "为 Seedance 2 设计的多镜头提示词，生成夜间电影级街头赛车场景，聚焦驾驶员专注度、动态镜头运动和爆发式加速效果。",
      href: '/plugins/video-template-cinematic-street-racing-sequence-for-seedance-2/',
      poster: "/previews/plugins/video-template-cinematic-street-racing-sequence-for-seedance-2.jpg",
      kind: "视频",
    },
    {
      title: "古印度王国FPV视频",
      desc: "快节奏FPV无人机风格的电影化提示词，描绘神秘的印度王国、寺庙和丛林场景。",
      href: '/plugins/video-template-ancient-indian-kingdom-fpv-video/',
      poster: "/previews/plugins/video-template-ancient-indian-kingdom-fpv-video.jpg",
      kind: "视频",
    },
    {
      title: "赛博朋克游戏预告片脚本",
      desc: "生成赛博朋克游戏预告片的详细视频提示词，包含角色设计、UI动画和从白色虚空到贫民窟的环境转场。",
      href: '/plugins/video-template-cyberpunk-game-trailer-script/',
      poster: "/previews/plugins/video-template-cyberpunk-game-trailer-script.jpg",
      kind: "视频",
    },
    {
      title: "豪华超跑电影叙事",
      desc: "适用于 Seedance 2.0 的多镜头电影提示词，包含时尚男士、杜宾犬和复古超跑，场景设定在雾气弥漫的山区。",
      href: '/plugins/video-template-luxury-supercar-cinematic-narrative/',
      poster: "/previews/plugins/video-template-luxury-supercar-cinematic-narrative.jpg",
      kind: "视频",
    },
    {
      title: "电影级龙与人互动与飞行",
      desc: "分镜脚本风格的视频提示词，展现女性与龙的情感互动及电影级飞行场景。",
      href: '/plugins/video-template-cinematic-dragon-interaction-flight/',
      poster: "/previews/plugins/video-template-cinematic-dragon-interaction-flight.jpg",
      kind: "视频",
    },
    {
      title: "电影风格吸血鬼巷战打斗场景",
      desc: "用于短片场景的综合动作提示词，包含霓虹灯照明小巷中的动态镜头运动和高速格斗。",
      href: '/plugins/video-template-cinematic-vampire-alley-fight-sequence/',
      poster: "/previews/plugins/video-template-cinematic-vampire-alley-fight-sequence.jpg",
      kind: "视频",
    },
  ],
  'solo-builder': [
    {
      title: "SaaS 落地页",
      desc: "单页 SaaS 落地页，包含主视觉、功能特性、社会证明、价格方案和行动号召。遵循当前 DESIGN.md 的颜色/排版/布局规范。触发关键词：\"saas landing\"、\"marketing page\"、\"product landing\"。",
      href: '/plugins/example-saas-landing/',
      poster: "/previews/plugins/example-saas-landing.jpg",
      kind: "原型",
    },
    {
      title: "网页原型",
      desc: "通用桌面网页原型。通过复制种子文件 `assets/template.html` 并粘贴 `references/layouts.md` 中的布局生成单个独立 HTML 文件。适用于落地页、营销页、文档或 SaaS 页面的默认选项。",
      href: '/plugins/example-web-prototype/',
      poster: "/previews/plugins/example-web-prototype.jpg",
      kind: "原型",
    },
    {
      title: "移动应用",
      desc: "在页面中渲染于像素级精确的 iPhone 15 Pro 框架内的移动应用屏幕。通过复制种子文件 assets/template.html 并粘贴 references/layouts.md 中的一个屏幕原型来构建。当需求提到《移动应用》、《iOS 应用》、《Android 应用》、《手机屏幕》或《应用 UI》时使用。",
      href: '/plugins/example-mobile-app/',
      poster: "/previews/plugins/example-mobile-app.jpg",
      kind: "原型",
    },
    {
      title: "仪表盘",
      desc: "单文件 HTML 管理/分析仪表盘。固定左侧边栏，顶部用户/搜索栏，主区域显示 KPI 卡片网格和图表。适用于需要'仪表盘'、'管理后台'、'数据分析'或'控制面板'界面的场景。",
      href: '/plugins/example-dashboard/',
      poster: "/previews/plugins/example-dashboard.jpg",
      kind: "原型",
    },
    {
      title: "博客文章",
      desc: "长篇文章/博客——包含页眉、主图占位符、带插图和引用的正文、作者署名及相关文章推荐。适用于需求中包含'博客'、'文章'、'帖子'、'随笔'或'案例研究'等关键词时。",
      href: '/plugins/example-blog-post/',
      poster: "/previews/plugins/example-blog-post.jpg",
      kind: "原型",
    },
    {
      title: "像世界级 Staff Engineer 一样写架构评审",
      desc: "像世界级 Staff Engineer 一样写架构评审——一份可商业交付的产品管理 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-deck-open-slide-canvas/',
      poster: "/previews/plugins/example-deck-open-slide-canvas.jpg",
      kind: "演示文稿",
    },
  ],
  'designer': [
    {
      title: "Web Prototype Taste 编辑风格",
      desc: "极简编辑风格网页原型。暖色单色调画布，衬线标题配无衬线正文，1px 细线边框，柔和粉彩色块，大量留白，微妙动效。",
      href: '/plugins/example-web-prototype-taste-editorial/',
      poster: "/previews/plugins/example-web-prototype-taste-editorial.jpg",
      kind: "原型",
    },
    {
      title: "Web Prototype Taste Brutalist",
      desc: "瑞士工业印刷风格网页原型。新闻纸画布、黑色粗体字、溢出式数字、细线网格分隔、危险红强调色、ASCII 语法装饰。源自 Leonxlnx/taste-skill `brutalist-skill`（瑞士工业印刷模式）。",
      href: '/plugins/example-web-prototype-taste-brutalist/',
      poster: "/previews/plugins/example-web-prototype-taste-brutalist.jpg",
      kind: "原型",
    },
    {
      title: "移动端引导",
      desc: "多屏幕移动引导流程，呈现为三个并排的手机框架——启动页、价值主张、登录页。包含状态栏、滑动指示点和主要CTA按钮。适用于需要'移动端引导'、'iOS引导'、'手机注册'或'移动端引导'的场景。",
      href: '/plugins/example-mobile-onboarding/',
      poster: "/previews/plugins/example-mobile-onboarding.jpg",
      kind: "原型",
    },
    {
      title: "线框草图",
      desc: "手绘风格的线框图，包含方格纸背景、马克笔/铅笔质感、多标签页变体、便签注释、图表占位符和阴影填充。适用于「线框图」「草图线框」「手绘」「低保真」「白板」「草稿」「手绘原型」等需求。",
      href: '/plugins/example-wireframe-sketch/',
      poster: "/previews/plugins/example-wireframe-sketch.jpg",
      kind: "原型",
    },
    {
      title: "Web Prototype Taste Soft",
      desc: "Apple 级柔和风格网页原型。银灰/奶油色画布，双边框卡片，嵌套按钮 CTA，大圆角，弹性动效和环境网格。基于 Leonxlnx/taste-skill 的 soft-skill 及第 4-8 节。",
      href: '/plugins/example-web-prototype-taste-soft/',
      poster: "/previews/plugins/example-web-prototype-taste-soft.jpg",
      kind: "原型",
    },
    {
      title: "图像海报",
      desc: "用于海报、主视觉和编辑插图的单图生成工具。默认使用 gpt-image-2，但支持通过上游工具切换至 Flux、Imagen 或 Midjourney。输出为保存到项目文件夹的 PNG/JPEG 文件。",
      href: '/plugins/example-image-poster/',
      poster: "/previews/plugins/example-image-poster.jpg",
      kind: "图像",
    },
  ],
  'engineering': [
    {
      title: "文档页面",
      desc: "文档页面 — 侧边导航、可滚动正文和目录。当需求提到'文档'、'指南'、'API 参考'或'教程'时使用。",
      href: '/plugins/example-docs-page/',
      poster: "/previews/plugins/example-docs-page.jpg",
      kind: "原型",
    },
    {
      title: "工程运维手册",
      desc: "工程运维手册 — 包含服务概览、告警表、仪表盘链接、常用命令操作步骤、值班轮换和事故响应清单。适用于需要运维文档、值班指南、SRE 文档或运维手册的场景。",
      href: '/plugins/example-eng-runbook/',
      poster: "/previews/plugins/example-eng-runbook.jpg",
      kind: "原型",
    },
    {
      title: "像平台 VP 一样把事故复盘写成学习稿",
      desc: "像平台 VP 一样把事故复盘写成学习稿——一份可商业交付的产品管理 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-knowledge-arch-blueprint/',
      poster: "/previews/plugins/example-html-ppt-knowledge-arch-blueprint.jpg",
      kind: "演示文稿",
    },
    {
      title: "像 Staff DevRel 一样做工程分享",
      desc: "像 Staff DevRel 一样做工程分享——一份可商业交付的AI 素养 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-tech-sharing/',
      poster: "/previews/plugins/example-html-ppt-tech-sharing.jpg",
      kind: "演示文稿",
    },
    {
      title: "数据可视化报告",
      desc: "把 CSV/Excel/JSON 数据转成漂亮的可视化报告页",
      href: '/plugins/example-data-report/',
      poster: "/previews/plugins/example-data-report.jpg",
      kind: "原型",
    },
    {
      title: "看板",
      desc: "看板/任务面板，包含多个列（待办/进行中/审核中/已完成）、可拖动样式的卡片、成员头像、泳道和顶部筛选栏。当需求中提到'kanban'、'task board'、'sprint board'、'trello'、'看板'时使用。",
      href: '/plugins/example-kanban-board/',
      poster: "/previews/plugins/example-kanban-board.jpg",
      kind: "原型",
    },
  ],
  'product-managers': [
    {
      title: "产品规格文档",
      desc: "单页产品规格文档/PRD——包含问题定义、成功指标、范围、用户故事、设计笔记、上线计划、待解决问题。适用于需求文档、产品规格、功能说明等场景。",
      href: '/plugins/example-pm-spec/',
      poster: "/previews/plugins/example-pm-spec.jpg",
      kind: "原型",
    },
    {
      title: "团队 OKR",
      desc: "OKR 跟踪页面——季度横幅，三个目标及其关键结果进度条、负责人头像、状态标签，以及「本季度概览」侧边栏。当需求提及 OKR、关键结果、目标时使用。",
      href: '/plugins/example-team-okrs/',
      poster: "/previews/plugins/example-team-okrs.jpg",
      kind: "原型",
    },
    {
      title: "像克制的 COO 一样写经营复盘",
      desc: "像克制的 COO 一样写经营复盘——一份可商业交付的企业战略 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-simple-deck/',
      poster: "/previews/plugins/example-simple-deck.jpg",
      kind: "演示文稿",
    },
    {
      title: "iPhone × MacBook 立体展架",
      desc: "iPhone + MacBook 仿 GLTF 静态展架, 屏幕内嵌真实 HTML 内容, 玻璃镜头折射, 360° 转盘构图",
      href: '/plugins/example-mockup-device-3d/',
      poster: "/previews/plugins/example-mockup-device-3d.jpg",
      kind: "原型",
    },
    {
      title: "像数据驱动的运营负责人一样开指标站会",
      desc: "像数据驱动的运营负责人一样开指标站会——一份可商业交付的数据财务 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-weekly-update/',
      poster: "/previews/plugins/example-weekly-update.jpg",
      kind: "演示文稿",
    },
    {
      title: "会议纪要",
      desc: "会议记录页面——包含与会者标题栏、议程清单、决策事项区块、带负责人和日期的行动项表格，以及'下次会议'页脚。适用于需要'会议纪要'、'会议记录'、'1:1 笔记'、'全员会议总结'或'minutes'的场景。",
      href: '/plugins/example-meeting-notes/',
      poster: "/previews/plugins/example-meeting-notes.jpg",
      kind: "原型",
    },
  ],
  'marketing': [
    {
      title: "像战略客户 AE 一样推动团队落地",
      desc: "像战略客户 AE 一样推动团队落地——一份可商业交付的B2B 销售 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-product-launch/',
      poster: "/previews/plugins/example-html-ppt-product-launch.jpg",
      kind: "演示文稿",
    },
    {
      title: "电子邮件营销",
      desc: "品牌产品发布电子邮件模板，包含报头、主图、斜体强调标题、正文、主要行动号召按钮和规格表格，采用HTML居中单栏布局。",
      href: '/plugins/example-email-marketing/',
      poster: "/previews/plugins/example-email-marketing.jpg",
      kind: "原型",
    },
    {
      title: "像晋升评审内部人一样写 Staff 工程师晋升材料",
      desc: "像晋升评审内部人一样写 Staff 工程师晋升材料——一份可商业交付的职业发展 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-xhs-white-editorial/',
      poster: "/previews/plugins/example-html-ppt-xhs-white-editorial.jpg",
      kind: "演示文稿",
    },
    {
      title: "数字电子指南",
      desc: "双页数字电子指南预览——第1页为封面（显示标题、作者、'内含什么'统计信息、目录预览）；第2页为内页（课程正文含引用语和步骤列表）。生活方式/创作者品牌风格。适用于需要'电子指南'、'数字指南'、'lookbook'、'引流素材'、'创作者指南'、'手册'或'PDF指南'的需求。",
      href: '/plugins/example-digital-eguide/',
      poster: "/previews/plugins/example-digital-eguide.jpg",
      kind: "原型",
    },
    {
      title: "像世界级 CMO 一样写年度营销计划",
      desc: "像世界级 CMO 一样写年度营销计划——一份可商业交付的市场增长 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-deck-guizang-editorial/',
      poster: "/previews/plugins/example-deck-guizang-editorial.jpg",
      kind: "演示文稿",
    },
    {
      title: "社交媒体轮播图",
      desc: "三张 1080×1080 方形社交媒体轮播卡片——三个富有电影感和品牌调性的面板，配有连贯的展示标题（'往前走。' → '到下一个。' → '展望未来。'）。每张卡片包含品牌标识、序号/总数、说明文字和'循环'提示。适用于'轮播帖子'、'社交媒体轮播'、'Instagram 轮播'、'LinkedIn 系列'、'X 系列卡片'或'三连发'等需求。",
      href: '/plugins/example-social-carousel/',
      poster: "/previews/plugins/example-social-carousel.jpg",
      kind: "原型",
    },
  ],
  'html-to-ppt': [
    {
      title: "像世界级 CMO 一样写年度营销计划",
      desc: "像世界级 CMO 一样写年度营销计划——一份可商业交付的市场增长 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-deck-guizang-editorial/',
      poster: "/previews/plugins/example-deck-guizang-editorial.jpg",
      kind: "演示文稿",
    },
    {
      title: "像财富 500 强董事长一样写董事会预读",
      desc: "像财富 500 强董事长一样写董事会预读——一份可商业交付的企业战略 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-deck-swiss-international/',
      poster: "/previews/plugins/example-deck-swiss-international.jpg",
      kind: "演示文稿",
    },
    {
      title: "像顶级加速器合伙人一样写 Demo Day 路演",
      desc: "像顶级加速器合伙人一样写 Demo Day 路演——一份可商业交付的融资路演 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-pitch-deck/',
      poster: "/previews/plugins/example-html-ppt-pitch-deck.jpg",
      kind: "演示文稿",
    },
    {
      title: "像战略客户 AE 一样推动团队落地",
      desc: "像战略客户 AE 一样推动团队落地——一份可商业交付的B2B 销售 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-product-launch/',
      poster: "/previews/plugins/example-html-ppt-product-launch.jpg",
      kind: "演示文稿",
    },
    {
      title: "像 Staff DevRel 一样做工程分享",
      desc: "像 Staff DevRel 一样做工程分享——一份可商业交付的AI 素养 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-tech-sharing/',
      poster: "/previews/plugins/example-html-ppt-tech-sharing.jpg",
      kind: "演示文稿",
    },
    {
      title: "像晋升评审内部人一样写 Staff 工程师晋升材料",
      desc: "像晋升评审内部人一样写 Staff 工程师晋升材料——一份可商业交付的职业发展 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-xhs-white-editorial/',
      poster: "/previews/plugins/example-html-ppt-xhs-white-editorial.jpg",
      kind: "演示文稿",
    },
    {
      title: "像一线 VC 合伙人一样写 A 轮增长叙事",
      desc: "像一线 VC 合伙人一样写 A 轮增长叙事——一份可商业交付的融资路演 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-zhangzara-bold-poster/',
      poster: "/previews/plugins/example-html-ppt-zhangzara-bold-poster.jpg",
      kind: "演示文稿",
    },
    {
      title: "像杂志艺术总监一样搭建编辑设计系统",
      desc: "像杂志艺术总监一样搭建编辑设计系统——一份可商业交付的设计打磨 Deck，围绕真实主题、证据链与决策目标组织。",
      href: '/plugins/example-html-ppt-zhangzara-editorial-tri-tone/',
      poster: "/previews/plugins/example-html-ppt-zhangzara-editorial-tri-tone.jpg",
      kind: "演示文稿",
    },
  ],
};

export type DesignSystemCard = { name: string; category: string; tagline: string; palette?: string[]; href: string };

export const DESIGN_SYSTEM_CARDS: DesignSystemCard[] = [
  {
    name: "Apple",
    category: "媒体与消费",
    tagline: "消费电子。极致留白，SF Pro 字体，电影级视觉。",
    palette: ["#ffffff", "#f5f5f7", "#fbfbfd", "#1d1d1f"],
    href: '/plugins/design-system-apple/',
  },
  {
    name: "Linear",
    category: "效率与 SaaS",
    tagline: "项目管理。超极简，精准，紫色点缀。",
    palette: ["#08090a", "#191a1b", "#f7f8f8", "#5e6ad2"],
    href: '/plugins/design-system-linear-app/',
  },
  {
    name: "Notion",
    category: "效率与 SaaS",
    tagline: "全能工作空间。暖调极简，衬线标题，柔和界面。",
    palette: ["#ffffff", "#f6f5f4", "#0075de", "#005bab"],
    href: '/plugins/design-system-notion/',
  },
  {
    name: "Figma",
    category: "设计与创意",
    tagline: "协作设计工具。鲜明多色，活泼又专业。",
    palette: ["#ffffff", "#000000"],
    href: '/plugins/design-system-figma/',
  },
  {
    name: "OpenAI",
    category: "AI 与大模型",
    tagline: "平静的近单色系统，以深青黑为基底，充足留白，编辑感排版。",
    palette: ["#ffffff", "#f5f5f5", "#fafafa", "#0d0d0d"],
    href: '/plugins/design-system-openai/',
  },
  {
    name: "GitHub",
    category: "开发者工具",
    tagline: "代码优先平台。功能密度，蓝白精准，Primer 设计基础。",
    palette: ["#ffffff", "#f6f8fa", "#1f2328", "#0969da"],
    href: '/plugins/design-system-github/',
  },
  {
    name: "Airbnb",
    category: "电商与零售",
    tagline: "旅行市场平台。暖珊瑚色点缀，摄影驱动，圆角 UI。",
    palette: ["#ffffff", "#f7f7f7", "#222222", "#ff385c"],
    href: '/plugins/design-system-airbnb/',
  },
  {
    name: "Vercel",
    category: "开发者工具",
    tagline: "前端部署。黑白精准，Geist 字体。",
    palette: ["#ffffff", "#171717", "#0070f3"],
    href: '/plugins/design-system-vercel/',
  },
  {
    name: "Stripe",
    category: "金融科技与加密",
    tagline: "支付基础设施。标志性紫色渐变，300 字重优雅感。",
    palette: ["#ffffff", "#f6f9fc", "#061b31", "#533afd"],
    href: '/plugins/design-system-stripe/',
  },
];
